version: '0.1'

services:
  db:
    image: postgres
    ports:
      - 5462:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on: 
      - rabbitmq_server

  backend:
    build: .
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        sleep 20
        python manage.py makemigrations
        python manage.py migrate
        if [ "$DJANGO_SUPERUSER_USERNAME" ] && [ "$DJANGO_SUPERUSER_EMAIL" ] && [ "$DJANGO_SUPERUSER_PASSWORD" ]; then
          python manage.py createsuperuser --noinput || true
        fi
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - worker