version: '0.1'

services:
  db:
    image: postgres
    ports:
      - 5462:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${YAYA_DB_NAME}
      - POSTGRES_USER=${YAYA_DB_USERNAME}
      - POSTGRES_PASSWORD=${YAYA_DB_PASSWORD}

  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on: 
      - rabbitmq_server

  backend:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
      - worker