version: '0.1'

services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - YAYA_API_URL=https://yayawallet.com/api/en
      - YAYA_API_PATH=/api/en
      - YAYA_API_KEY=key-test_19aca8ac-7925-4438-9ece-e54b6fc31d61
      - YAYA_API_SECRET=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcGlfa2V5Ijoia2V5LXRlc3RfMTlhY2E4YWMtNzkyNS00NDM4LTllY2UtZTU0YjZmYzMxZDYxIiwic2VjcmV0IjoiM2QwMWU3ZTcxNDVkYTRhY2RlMmM2MzA3NzRhMjFjODU0ZmFkNzIwZCJ9.-Zy7J39-3VIlmtr-6ROpF2nN1b0C5Dzh7iOc2rdzXbQ

  frontend:
    image: ermadock/yayawallet-sdk-frontend:latest
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - VITE_BASE_URL=http://localhost:8000