SCHEDULED = "SCHEDULED"
CONTRACT = "CONTRACT"
REQUEST_PAYMENT= "REQUEST_PAYMENT"
BILL= "BILL"
PAYOUT= "PAYOUT"

ImportTypes = {
  SCHEDULED: "Scheduled Payment",
  CONTRACT :"Recurring Contract",
  REQUEST_PAYMENT: "Request Payment",
  BILL: "Bill",
  PAYOUT: "PAYOUT",
}

TRANSACTION = "TRANSACTION"
TRANSFER = "TRANSFER"
AIRTIME = "AIRTIME"
PACKAGE = "PACKAGE"
BILL_ACTION = "BILL_ACTION"
SCHEDULED_ACTION = "SCHEDULED_ACTION"
CONTRACT_ACTION = "CONTRACT_ACTION"
REQUEST_PAYMENT_ACTION = "REQUEST_PAYMENT_ACTION"

Actions = {
  TRANSACTION: "Transaction on YaYa",
  TRANSFER: "Transfer To Other Bank",
  AIRTIME: "Airtime Purchase",
  PACKAGE: "Package Purchase",
  BILL_ACTION: "Bill Creation",
  SCHEDULED_ACTION: "Scheduled Payment Creation",
  CONTRACT_ACTION: "Contract Creation",
  REQUEST_PAYMENT_ACTION: "Request Payment Action",
}

SCHEDULED_BULK_IMPORT = "SCHEDULED_BULK_IMPORT"
CONTRACT_BULK_IMPORT = "CONTRACT_BULK_IMPORT"
REQUEST_PAYMENT_BULK_IMPORT = "REQUEST_PAYMENT_BULK_IMPORT"
SCHEDULED = "SCHEDULED"
TRANSACTION = "TRANSACTION"
TRANSFER = "TRANSFER"
CONTRACT = "CONTRACT"
REQUEST_PAYMENT = "REQUEST_PAYMENT"
AIRTIME = "AIRTIME"
PACKAGE = "PACKAGE"

Requests = {
  SCHEDULED_BULK_IMPORT: "Scheduled Bulk Import",
  CONTRACT_BULK_IMPORT: "Contract Bulk Import",
  REQUEST_PAYMENT_BULK_IMPORT: "Request Payment Bulk Import",
  SCHEDULED: "Scheduled",
  TRANSACTION: "Transaction",
  TRANSFER: "Transfer",
  CONTRACT: "Contract",
  REQUEST_PAYMENT: "Request Payment",
  AIRTIME: "Airtime",
  PACKAGE: "Package",
}

Approve = "Approve"
Reject = "Reject"
Pending = "PENDING"