SCHEDULED = "SCHEDULED"
CONTRACT = "CONTRACT"
REQUEST_PAYMENT= "REQUEST_PAYMENT"
BILL= "BILL"
PAYOUT= "PAYOUT"

ImportTypes = {
  SCHEDULED: "Scheduled Payment",
  CONTRACT :"Recurring Contract",
  REQUEST_PAYMENT: "Request Payment",
  BILL: "Bill",
  PAYOUT: "PAYOUT",
}
