# Generated by Django 5.0 on 2024-05-20 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField()),
                ('amount', models.CharField()),
                ('reason', models.CharField()),
                ('recurring', models.CharField()),
                ('start_at', models.CharField()),
                ('meta_data', models.CharField()),
                ('json_object', models.CharField()),
                ('uploaded', models.BooleanField()),
            ],
        ),
    ]
