# Generated by Django 5.0.6 on 2024-07-11 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedDocuments',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField()),
                ('remark', models.CharField()),
                ('import_type', models.CharField()),
                ('failed_count', models.IntegerField(blank=True, null=True)),
                ('successful_count', models.IntegerField(blank=True, null=True)),
                ('on_queue_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FailedImports',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('json_object', models.CharField()),
                ('error_message', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.importeddocuments')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('client_yaya_account', models.CharField(blank=True, null=True)),
                ('customer_yaya_account', models.CharField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('start_at', models.IntegerField(blank=True, null=True)),
                ('due_at', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, null=True)),
                ('bill_id', models.CharField(blank=True, null=True)),
                ('bill_code', models.CharField(blank=True, null=True)),
                ('bill_season', models.CharField(blank=True, null=True)),
                ('cluster', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('details', models.CharField(blank=True, null=True)),
                ('json_object', models.CharField(blank=True, null=True)),
                ('uploaded', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.importeddocuments')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPaymentRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('contract_number', models.CharField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField()),
                ('cause', models.CharField()),
                ('notification_url', models.CharField()),
                ('meta_data', models.CharField()),
                ('json_object', models.CharField()),
                ('uploaded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.importeddocuments')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('account_number', models.CharField()),
                ('amount', models.FloatField()),
                ('reason', models.CharField()),
                ('recurring', models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10)),
                ('start_at', models.CharField()),
                ('meta_data', models.CharField()),
                ('json_object', models.CharField()),
                ('uploaded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.importeddocuments')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('contract_number', models.CharField()),
                ('service_type', models.CharField()),
                ('customer_account_name', models.CharField()),
                ('meta_data', models.CharField()),
                ('json_object', models.CharField()),
                ('uploaded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.importeddocuments')),
            ],
            options={
                'unique_together': {('contract_number', 'service_type')},
            },
        ),
        migrations.AddConstraint(
            model_name='scheduled',
            constraint=models.CheckConstraint(check=models.Q(('recurring__in', ['once', 'daily', 'weekly', 'monthly'])), name='recurring_valid_values'),
        ),
    ]
