# Generated by Django 5.0.6 on 2024-06-06 07:17

from django.db import migrations

def create_custom_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type = ContentType.objects.get_for_model(Permission)

    Permission.objects.create(
        codename='can_transfer_money',
        name='Can Transfer Money',
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_custom_permissions),
    ]
