# Generated by Django 5.0.6 on 2024-06-08 08:25

from django.db import migrations

def create_custom_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type = ContentType.objects.get_for_model(Permission)

    Permission.objects.create(
        codename='buy_airtime',
        name='Buy Airtime',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='buy_package',
        name='Buy Package',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_equb',
        name='Create Equb',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='update_equb',
        name='Update Equb',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_invitation',
        name='Create Invitation',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='get_invitation_otp',
        name='Get Invitation OTP',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_saving',
        name='Create Saving',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='claim',
        name='Claim',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='generate_qr_url',
        name='Generate QR Url',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='external_account_lookup',
        name='External Account Lookup',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_bill',
        name='Create Bill',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_bulk_bill',
        name='Create Bulk Bill',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='update_bill',
        name='Update Bill',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_user',
        name='Create User',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_payout',
        name='Can Create Payout',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='create_bulk_payout',
        name='Create Bulk Payout',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_bulk_schedule_import',
        name='Approval Bulk Schedule Import',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='bulk_schedule_request',
        name='Bulk Schedule Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='bulk_scheduled_requests',
        name='Bulk Scheduled Requests',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_bulk_contract_import',
        name='Approval Bulk Contract Import',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='bulk_contract_request',
        name='Bulk Contract Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='bulk_contract_requests',
        name='Bulk Contract Requests',
        content_type=content_type,
    )
    
    Permission.objects.create(
        codename='approval_bulk_payment_request_import',
        name='Approval Bulk Payment Request Import',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='bulk_payment_request',
        name='Bulk Payment Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='bulk_requested_payments',
        name='Bulk Requested Payments',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='schedule_request',
        name='Schedule Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_scheduled',
        name='Approval Scheduled',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='scheduled_requests',
        name='Scheduled Requests',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='contract_request',
        name='Contract Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_contract',
        name='Approval Contract',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='contract_requests',
        name='Contract Requests',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='payment_request',
        name='Payment Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_payment_request',
        name='Approval Payment Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='payment_requests',
        name='Payment Requests',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='transaction_request',
        name='Transaction Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_transaction',
        name='Approval Transaction',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='transaction_requests',
        name='Transaction Requests',
        content_type=content_type,
    )
    
    Permission.objects.create(
        codename='transfer_request',
        name='Transfer Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_transfer',
        name='Approval Transfer',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='transfer_requests',
        name='Transfer Requests',
        content_type=content_type,
    )
    Permission.objects.create(
        codename='airtime_request',
        name='Airtime Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='approval_airtime',
        name='Approval Airtime',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='airtime_requests',
        name='Airtime Requests',
        content_type=content_type,
    )
    
    Permission.objects.create(
        codename='package_request',
        name='Package Request',
        content_type=content_type,
    )

    Permission.objects.create(
        codename='can_access_admin',
        name='Can Access Admin',
        content_type=content_type,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_custom_permissions),
    ]
