# Generated by Django 5.0 on 2024-05-22 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField()),
                ('service_type', models.CharField()),
                ('customer_account_name', models.CharField()),
                ('meta_data', models.CharField()),
                ('json_object', models.CharField()),
                ('uploaded', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPaymentRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField()),
                ('cause', models.CharField()),
                ('notification_url', models.CharField()),
                ('meta_data', models.CharField()),
                ('json_object', models.CharField()),
                ('uploaded', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='scheduled',
            name='amount',
            field=models.FloatField(),
        ),
    ]
