# Generated by Django 5.0.6 on 2024-06-06 08:05

from django.db import migrations

def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, _ = Group.objects.get_or_create(name="Admin")

    permission = Permission.objects.get(codename="can_transfer_money")

    group.permissions.add(permission)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_create_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
