# Generated by Django 5.0.6 on 2024-05-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_contract_recurringpaymentrequest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('contract_number', 'customer_account_name')},
        ),
    ]
