# Generated by Django 5.0.6 on 2024-05-27 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_contract_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedContract',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json_object', models.CharField()),
            ],
        ),
    ]
