# Generated by Django 5.0.6 on 2024-06-08 08:27

from django.db import migrations

def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    group, _ = Group.objects.get_or_create(name="Clerk")

    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_create_group'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
