# Generated by Django 5.0.6 on 2024-07-08 12:47

from django.db import migrations

def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, _ = Group.objects.get_or_create(name="Agent")

    create_user = Permission.objects.get(codename="create_user")
    create_invitation = Permission.objects.get(codename="create_invitation")
    get_invitation_otp = Permission.objects.get(codename="get_invitation_otp")

    group.permissions.add(create_user)
    group.permissions.add(create_invitation)
    group.permissions.add(get_invitation_otp)
    group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_create_clerk_group'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]


