name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yayawallet/python-server:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yayawallet/background-service:latest
          file: worker.Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run commands on ECS server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S cd /root/dashboard/yayawallet-dashboard &&
          docker-compose pull &&
          docker-compose up -d --no-deps worker backend
          '
