name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yayawallet/python-server:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yayawallet/background-service:latest
          file: worker.Dockerfile
          platforms: linux/amd64,linux/arm64
